import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './Header'
import Nav from './Nav';
import AboutMe from './AboutMe'
import Works from './Works'
import Contact from './Contact'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css?family=Cherry+Swash:700" rel="stylesheet"/>
      <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet"/>
    </Head>
    <Header/>
    <Nav/>
    <AboutMe/>
    <Works/>
    <Contact/>
    <footer>
      <p>©️ 2021 Soichiro Kawamura</p>
    </footer>
    <style jsx>{`
      footer {
        background-color: rgb(34, 34, 77);
        height: 100px;
        text-align: center;
      }
      footer p {
        padding-top: 60px;
        color: #fff;
      }
    `}
    </style>
    </>
  )
}
