import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './Header'
import Nav from './Nav';
import AboutMe from './AboutMe'
import Works from './Works'
import Contact from './Contact'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css?family=Cherry+Swash:700" rel="stylesheet"/>
      <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet"/>
      <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet"/>
    </Head>
    <Header/>
    <Nav/>
    <AboutMe/>
    <Works/>
    <Contact/>
    <footer className={styles.footer}>
      <p>©️ 2021 Soichiro Kawamura</p>
    </footer>
    </>
  )
}
